# -*- coding: utf-8 -*-
"""AI-A2-heuristics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dOsxczsKJbr6zlyDk4tL10IUMMc5VoPz
"""

import pandas as pd
import geopy.distance
from google.colab import files

distances = pd.read_csv('A2_roaddistance.csv')

l2 = list(distances.columns)

l1 = list(distances['Distance in Kilometres'])

s1 = set().union(l1, l2)

city_names = list(s1)

df = []
for city in city_names:
    print(city)
    lat = float(input())
    lon = float(input())
    df.append([city, lon, lat])

finalData = []
for i in range(len(df)):
    city_name = df[i][0]
    city_lat = df[i][1]
    city_long = df[i][2]

    for j in range(len(df)):
        sec_name = df[j][0]
        sec_lat = df[j][1]
        sec_long = df[j][2]

        c1 = (city_long, city_lat)
        c2 = (sec_long, sec_lat)
        dist = geopy.distance.distance(c1, c2).km
        finalData.append([city_name, sec_name, dist])

finalDF = pd.DataFrame(finalData)

finalDF.to_csv('heuristics.csv')

files.download("heuristics.csv")